/******************Oracle***********************/
  CREATE TABLE "ROOT"."CUSTOMER" 
   (	"CUSTNO" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CUSTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUSTADDRS" VARCHAR2(20 BYTE), 
	"BILLAMT" FLOAT(126)
   );


   CREATE SEQUENCE  "ROOT"."CUSTOMER_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

   
/******************MySql***********************/
CREATE TABLE `layered_customer` (
  `CUSTNO` int NOT NULL DEFAULT '1',
  `CUSTNAME` varchar(20) NOT NULL,
  `CUSTADDRS` varchar(20) NOT NULL,
  `BILLAMT` float DEFAULT NULL,
  UNIQUE KEY `CUSTNO_UNIQUE` (`CUSTNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

   
   