spring:
  profiles:
    active: prod

---
spring:
  profiles: dev
  datasource:
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///spring
    username: root
---
spring:
  profiles: test
  datasource:
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///spring
    username: root
---  
spring:
  profiles: uat
  datasource:
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: root
---
spring:
  profiles: prod
  datasource:
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: root
